### ISSUE TITLE
若干建议

### ISSUE THREAD

**Issue by sinchb** [liubin/dockerbook-bugs#1]
1. p69
   下半页，Docker可以再宿主机上随机选择一个位于49000~49900的一个比较大的端口号，而官方 [文档](http://docs.docker.com/userguide/dockerlinks/#network-port-mapping-refresher) 似乎是49152~65535
2. p37
   最上面，“Docker **以** 在hosts文件中为...”，这个 **“以”** 是不是应该是 **“已”**
3. p111
   最后一段最后一句：“在这个模型里，容器化的应用程序限制了可被攻击的界面，减少了公开暴露的网络”，其实原文是“we now have a very strong security model for limiting the attack surface and network exposure of a containerized application”。我认为attack surface翻译成“攻击的界面”似乎不妥。另外就是我认为，不应该是“容器化的应用程序限制了....”，而应该是“security mode”限制了"containerized application"的"attack surface" 和 "network exposure"，可能主语搞错了.
4. P134
   代码清单6-2中，"var/www/html"应该是"/var/www/html"
5. P147
   最后一段，“因为这个应用回直接和Docker......, 于是，那也正式安装Ruby的地方”，这句话读着很别扭。 原文是"We're going to install our TProv application on our Docker host because our application is going to be directly interacting with our Docker daemon, so that's where we need to install Ruby."，我想作者的意思应该是“我们在宿主机上安装TProv应用，是因为我们的应用会直接和Docker守护进程交互。这也是我们要安装Ruby的原因”. PS(个人建议)
6. P154
   代码清单 6-37 最后的  `CMD[ ]` 在作者文档中已经消失了，其实也是多余的。

**Comment by liubin** [comment]
1. the -P flag was used to automatically map any network ports inside it to a random high port from the range 49153 to 65535 on our Docker host.

应该是49153~65535
1. "以"应该为“已”
2. 1. 待Lee确认
3. 和 6. 应该如同指出来的那样，修改或删除。
